receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource:
    attributes:
    - key: appdynamics.controller.account
      action: upsert
      value: "devnet"
    - key: appdynamics.controller.host
      action: upsert
      value: "devnet.saas.appdynamics.com"
    - key: appdynamics.controller.port
      action: upsert
      value: 443
    - key: service.namespace
      action: upsert
      value: "astronomyshop"
  batch:
    timeout: 60s
    send_batch_size: 10

exporters:
  otlphttp:
    endpoint: "https://pdx-sls-agent-api.saas.appdynamics.com"
    headers: {"x-api-key": "mykey"}
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp]
  telemetry:
    logs:
      level: "DEBUG"
